// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sessionMembersFieldNames          = builder.RawFieldNames(&SessionMembers{})
	sessionMembersRows                = strings.Join(sessionMembersFieldNames, ",")
	sessionMembersRowsExpectAutoSet   = strings.Join(stringx.Remove(sessionMembersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sessionMembersRowsWithPlaceHolder = strings.Join(stringx.Remove(sessionMembersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sessionMembersModel interface {
		Insert(ctx context.Context, data *SessionMembers) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SessionMembers, error)
		Update(ctx context.Context, data *SessionMembers) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSessionMembersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SessionMembers struct {
		Id          int64     `db:"id"`
		SessionUuid string    `db:"session_uuid"`
		UserUuid    string    `db:"user_uuid"`
		CreatedAt   time.Time `db:"created_at"`
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newSessionMembersModel(conn sqlx.SqlConn) *defaultSessionMembersModel {
	return &defaultSessionMembersModel{
		conn:  conn,
		table: "`session_members`",
	}
}

func (m *defaultSessionMembersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSessionMembersModel) FindOne(ctx context.Context, id int64) (*SessionMembers, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sessionMembersRows, m.table)
	var resp SessionMembers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSessionMembersModel) Insert(ctx context.Context, data *SessionMembers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, sessionMembersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SessionUuid, data.UserUuid)
	return ret, err
}

func (m *defaultSessionMembersModel) Update(ctx context.Context, data *SessionMembers) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sessionMembersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.SessionUuid, data.UserUuid, data.Id)
	return err
}

func (m *defaultSessionMembersModel) tableName() string {
	return m.table
}
