// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sessionsFieldNames          = builder.RawFieldNames(&Sessions{})
	sessionsRows                = strings.Join(sessionsFieldNames, ",")
	sessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(sessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sessionsRowsWithPlaceHolder = strings.Join(stringx.Remove(sessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sessionsModel interface {
		Insert(ctx context.Context, data *Sessions) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Sessions, error)
		Update(ctx context.Context, data *Sessions) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSessionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Sessions struct {
		Id          int64     `db:"id"`
		Uuid        string    `db:"uuid"`
		Name        string    `db:"name"`
		Avatar      string    `db:"avatar"`
		SessionType int64     `db:"session_type"`
		Status      int64     `db:"status"`
		CreatedAt   time.Time `db:"created_at"`
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newSessionsModel(conn sqlx.SqlConn) *defaultSessionsModel {
	return &defaultSessionsModel{
		conn:  conn,
		table: "`sessions`",
	}
}

func (m *defaultSessionsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSessionsModel) FindOne(ctx context.Context, id int64) (*Sessions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sessionsRows, m.table)
	var resp Sessions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSessionsModel) Insert(ctx context.Context, data *Sessions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, sessionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Uuid, data.Name, data.Avatar, data.SessionType, data.Status)
	return ret, err
}

func (m *defaultSessionsModel) Update(ctx context.Context, data *Sessions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sessionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Uuid, data.Name, data.Avatar, data.SessionType, data.Status, data.Id)
	return err
}

func (m *defaultSessionsModel) tableName() string {
	return m.table
}
