// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.20.3
// source: plato.proto

package plato

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageUpLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionUuid string `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"` // 会话UUID
	Payload     string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                            // 消息
}

func (x *MessageUpLink) Reset() {
	*x = MessageUpLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plato_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUpLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpLink) ProtoMessage() {}

func (x *MessageUpLink) ProtoReflect() protoreflect.Message {
	mi := &file_plato_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpLink.ProtoReflect.Descriptor instead.
func (*MessageUpLink) Descriptor() ([]byte, []int) {
	return file_plato_proto_rawDescGZIP(), []int{0}
}

func (x *MessageUpLink) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *MessageUpLink) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type MessageDownLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionUuid    string `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`            // 会话UUID
	SenderUserUuid string `protobuf:"bytes,2,opt,name=sender_user_uuid,json=senderUserUuid,proto3" json:"sender_user_uuid,omitempty"` // 发送者UUID
	Payload        string `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                       // 消息
	SeqId          int64  `protobuf:"varint,4,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`                             // 序列号ID 会话内有序
}

func (x *MessageDownLink) Reset() {
	*x = MessageDownLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plato_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageDownLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDownLink) ProtoMessage() {}

func (x *MessageDownLink) ProtoReflect() protoreflect.Message {
	mi := &file_plato_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDownLink.ProtoReflect.Descriptor instead.
func (*MessageDownLink) Descriptor() ([]byte, []int) {
	return file_plato_proto_rawDescGZIP(), []int{1}
}

func (x *MessageDownLink) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *MessageDownLink) GetSenderUserUuid() string {
	if x != nil {
		return x.SenderUserUuid
	}
	return ""
}

func (x *MessageDownLink) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *MessageDownLink) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type MessageCreateConn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 用户token
}

func (x *MessageCreateConn) Reset() {
	*x = MessageCreateConn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plato_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageCreateConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCreateConn) ProtoMessage() {}

func (x *MessageCreateConn) ProtoReflect() protoreflect.Message {
	mi := &file_plato_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCreateConn.ProtoReflect.Descriptor instead.
func (*MessageCreateConn) Descriptor() ([]byte, []int) {
	return file_plato_proto_rawDescGZIP(), []int{2}
}

func (x *MessageCreateConn) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_plato_proto protoreflect.FileDescriptor

var file_plato_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x6c, 0x61, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55,
	0x70, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x8f, 0x01, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x6f,
	0x77, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x55,
	0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73,
	0x65, 0x71, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x6c, 0x61, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_plato_proto_rawDescOnce sync.Once
	file_plato_proto_rawDescData = file_plato_proto_rawDesc
)

func file_plato_proto_rawDescGZIP() []byte {
	file_plato_proto_rawDescOnce.Do(func() {
		file_plato_proto_rawDescData = protoimpl.X.CompressGZIP(file_plato_proto_rawDescData)
	})
	return file_plato_proto_rawDescData
}

var file_plato_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plato_proto_goTypes = []interface{}{
	(*MessageUpLink)(nil),     // 0: plato.MessageUpLink
	(*MessageDownLink)(nil),   // 1: plato.MessageDownLink
	(*MessageCreateConn)(nil), // 2: plato.MessageCreateConn
}
var file_plato_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plato_proto_init() }
func file_plato_proto_init() {
	if File_plato_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plato_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUpLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plato_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageDownLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plato_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageCreateConn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plato_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plato_proto_goTypes,
		DependencyIndexes: file_plato_proto_depIdxs,
		MessageInfos:      file_plato_proto_msgTypes,
	}.Build()
	File_plato_proto = out.File
	file_plato_proto_rawDesc = nil
	file_plato_proto_goTypes = nil
	file_plato_proto_depIdxs = nil
}
