// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: plato.proto

package plato

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageUpLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionUuid   string                 `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"` // 会话UUID
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                            // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUpLink) Reset() {
	*x = MessageUpLink{}
	mi := &file_plato_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpLink) ProtoMessage() {}

func (x *MessageUpLink) ProtoReflect() protoreflect.Message {
	mi := &file_plato_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpLink.ProtoReflect.Descriptor instead.
func (*MessageUpLink) Descriptor() ([]byte, []int) {
	return file_plato_proto_rawDescGZIP(), []int{0}
}

func (x *MessageUpLink) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *MessageUpLink) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type MessageDownLink struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionUuid    string                 `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`            // 会话UUID
	SenderUserUuid string                 `protobuf:"bytes,2,opt,name=sender_user_uuid,json=senderUserUuid,proto3" json:"sender_user_uuid,omitempty"` // 发送者UUID
	Payload        string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                       // 消息
	SeqId          int64                  `protobuf:"varint,4,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`                             // 序列号ID 会话内有序
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageDownLink) Reset() {
	*x = MessageDownLink{}
	mi := &file_plato_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDownLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDownLink) ProtoMessage() {}

func (x *MessageDownLink) ProtoReflect() protoreflect.Message {
	mi := &file_plato_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDownLink.ProtoReflect.Descriptor instead.
func (*MessageDownLink) Descriptor() ([]byte, []int) {
	return file_plato_proto_rawDescGZIP(), []int{1}
}

func (x *MessageDownLink) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *MessageDownLink) GetSenderUserUuid() string {
	if x != nil {
		return x.SenderUserUuid
	}
	return ""
}

func (x *MessageDownLink) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *MessageDownLink) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type MessageCreateConn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 用户token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCreateConn) Reset() {
	*x = MessageCreateConn{}
	mi := &file_plato_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCreateConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCreateConn) ProtoMessage() {}

func (x *MessageCreateConn) ProtoReflect() protoreflect.Message {
	mi := &file_plato_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCreateConn.ProtoReflect.Descriptor instead.
func (*MessageCreateConn) Descriptor() ([]byte, []int) {
	return file_plato_proto_rawDescGZIP(), []int{2}
}

func (x *MessageCreateConn) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_plato_proto protoreflect.FileDescriptor

const file_plato_proto_rawDesc = "" +
	"\n" +
	"\vplato.proto\x12\x05plato\"L\n" +
	"\rMessageUpLink\x12!\n" +
	"\fsession_uuid\x18\x01 \x01(\tR\vsessionUuid\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"\x8f\x01\n" +
	"\x0fMessageDownLink\x12!\n" +
	"\fsession_uuid\x18\x01 \x01(\tR\vsessionUuid\x12(\n" +
	"\x10sender_user_uuid\x18\x02 \x01(\tR\x0esenderUserUuid\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x15\n" +
	"\x06seq_id\x18\x04 \x01(\x03R\x05seqId\")\n" +
	"\x11MessageCreateConn\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05tokenB\n" +
	"Z\b./;platob\x06proto3"

var (
	file_plato_proto_rawDescOnce sync.Once
	file_plato_proto_rawDescData []byte
)

func file_plato_proto_rawDescGZIP() []byte {
	file_plato_proto_rawDescOnce.Do(func() {
		file_plato_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plato_proto_rawDesc), len(file_plato_proto_rawDesc)))
	})
	return file_plato_proto_rawDescData
}

var file_plato_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plato_proto_goTypes = []any{
	(*MessageUpLink)(nil),     // 0: plato.MessageUpLink
	(*MessageDownLink)(nil),   // 1: plato.MessageDownLink
	(*MessageCreateConn)(nil), // 2: plato.MessageCreateConn
}
var file_plato_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plato_proto_init() }
func file_plato_proto_init() {
	if File_plato_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plato_proto_rawDesc), len(file_plato_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plato_proto_goTypes,
		DependencyIndexes: file_plato_proto_depIdxs,
		MessageInfos:      file_plato_proto_msgTypes,
	}.Build()
	File_plato_proto = out.File
	file_plato_proto_goTypes = nil
	file_plato_proto_depIdxs = nil
}
