// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: rpc/service/imgateway.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelConnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        string                 `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"` // 连接ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelConnRequest) Reset() {
	*x = DelConnRequest{}
	mi := &file_rpc_service_imgateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelConnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelConnRequest) ProtoMessage() {}

func (x *DelConnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_imgateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelConnRequest.ProtoReflect.Descriptor instead.
func (*DelConnRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_imgateway_proto_rawDescGZIP(), []int{0}
}

func (x *DelConnRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type DelConnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelConnResponse) Reset() {
	*x = DelConnResponse{}
	mi := &file_rpc_service_imgateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelConnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelConnResponse) ProtoMessage() {}

func (x *DelConnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_imgateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelConnResponse.ProtoReflect.Descriptor instead.
func (*DelConnResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_imgateway_proto_rawDescGZIP(), []int{1}
}

var File_rpc_service_imgateway_proto protoreflect.FileDescriptor

const file_rpc_service_imgateway_proto_rawDesc = "" +
	"\n" +
	"\x1brpc/service/imgateway.proto\x12\timgateway\")\n" +
	"\x0eDelConnRequest\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\tR\x06connId\"\x11\n" +
	"\x0fDelConnResponse2M\n" +
	"\tIMGateway\x12@\n" +
	"\aDelConn\x12\x19.imgateway.DelConnRequest\x1a\x1a.imgateway.DelConnResponseB\fZ\n" +
	"./;serviceb\x06proto3"

var (
	file_rpc_service_imgateway_proto_rawDescOnce sync.Once
	file_rpc_service_imgateway_proto_rawDescData []byte
)

func file_rpc_service_imgateway_proto_rawDescGZIP() []byte {
	file_rpc_service_imgateway_proto_rawDescOnce.Do(func() {
		file_rpc_service_imgateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_service_imgateway_proto_rawDesc), len(file_rpc_service_imgateway_proto_rawDesc)))
	})
	return file_rpc_service_imgateway_proto_rawDescData
}

var file_rpc_service_imgateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_service_imgateway_proto_goTypes = []any{
	(*DelConnRequest)(nil),  // 0: imgateway.DelConnRequest
	(*DelConnResponse)(nil), // 1: imgateway.DelConnResponse
}
var file_rpc_service_imgateway_proto_depIdxs = []int32{
	0, // 0: imgateway.IMGateway.DelConn:input_type -> imgateway.DelConnRequest
	1, // 1: imgateway.IMGateway.DelConn:output_type -> imgateway.DelConnResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_service_imgateway_proto_init() }
func file_rpc_service_imgateway_proto_init() {
	if File_rpc_service_imgateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_service_imgateway_proto_rawDesc), len(file_rpc_service_imgateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_service_imgateway_proto_goTypes,
		DependencyIndexes: file_rpc_service_imgateway_proto_depIdxs,
		MessageInfos:      file_rpc_service_imgateway_proto_msgTypes,
	}.Build()
	File_rpc_service_imgateway_proto = out.File
	file_rpc_service_imgateway_proto_goTypes = nil
	file_rpc_service_imgateway_proto_depIdxs = nil
}
