services:
  mysql:
    image: mysql:8.4.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
    restart: always
  redis:  
    image: redis:8.2.2
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --requirepass root
    restart: always

volumes:
  mysql_data:
  redis_data: