services:
  api-gateway:
    image: comeonjy/im:latest
    ports:
      - 8088:8088
    env_file:
      - ../.prod.env
    # volumes:
    #   - ./bin:/app
    command: /app/im apigateway
  im-gateway:
    image: comeonjy/im:latest
    ports:
      - 8086:8086
    env_file:
      - ../.prod.env
    # volumes:
    #   - ./bin:/app
    command: /app/im imgateway
    depends_on:
      - api-gateway