// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: rpc/service/discovery.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`          // 服务名称
	ServiceAddress string                 `protobuf:"bytes,2,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"` // 服务地址
	ServicePort    string                 `protobuf:"bytes,3,opt,name=service_port,json=servicePort,proto3" json:"service_port,omitempty"`          // 服务端口
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_rpc_service_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterRequest) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

func (x *RegisterRequest) GetServicePort() string {
	if x != nil {
		return x.ServicePort
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_rpc_service_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_discovery_proto_rawDescGZIP(), []int{1}
}

type DeregisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`          // 服务名称
	ServiceAddress string                 `protobuf:"bytes,2,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"` // 服务地址
	ServicePort    string                 `protobuf:"bytes,3,opt,name=service_port,json=servicePort,proto3" json:"service_port,omitempty"`          // 服务端口
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_rpc_service_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DeregisterRequest) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

func (x *DeregisterRequest) GetServicePort() string {
	if x != nil {
		return x.ServicePort
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_rpc_service_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_discovery_proto_rawDescGZIP(), []int{3}
}

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 服务名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_rpc_service_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *GetServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceInfo   []*ServiceInfo         `protobuf:"bytes,1,rep,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"` // 服务列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceResponse) Reset() {
	*x = GetServiceResponse{}
	mi := &file_rpc_service_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceResponse) ProtoMessage() {}

func (x *GetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *GetServiceResponse) GetServiceInfo() []*ServiceInfo {
	if x != nil {
		return x.ServiceInfo
	}
	return nil
}

type GetServiceIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 服务名称
	ClientKey     string                 `protobuf:"bytes,2,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`       // 客户端唯一标识，用于负载均衡
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceIPRequest) Reset() {
	*x = GetServiceIPRequest{}
	mi := &file_rpc_service_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceIPRequest) ProtoMessage() {}

func (x *GetServiceIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceIPRequest.ProtoReflect.Descriptor instead.
func (*GetServiceIPRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_discovery_proto_rawDescGZIP(), []int{6}
}

func (x *GetServiceIPRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetServiceIPRequest) GetClientKey() string {
	if x != nil {
		return x.ClientKey
	}
	return ""
}

type GetServiceIPResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceAddress string                 `protobuf:"bytes,1,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"` // 服务地址
	ServicePort    string                 `protobuf:"bytes,2,opt,name=service_port,json=servicePort,proto3" json:"service_port,omitempty"`          // 服务端口
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetServiceIPResponse) Reset() {
	*x = GetServiceIPResponse{}
	mi := &file_rpc_service_discovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceIPResponse) ProtoMessage() {}

func (x *GetServiceIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_discovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceIPResponse.ProtoReflect.Descriptor instead.
func (*GetServiceIPResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_discovery_proto_rawDescGZIP(), []int{7}
}

func (x *GetServiceIPResponse) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

func (x *GetServiceIPResponse) GetServicePort() string {
	if x != nil {
		return x.ServicePort
	}
	return ""
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_rpc_service_discovery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_discovery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_discovery_proto_rawDescGZIP(), []int{8}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_rpc_service_discovery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_discovery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_discovery_proto_rawDescGZIP(), []int{9}
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type ServiceInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceAddress string                 `protobuf:"bytes,1,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"` // 服务地址
	ServicePort    string                 `protobuf:"bytes,2,opt,name=service_port,json=servicePort,proto3" json:"service_port,omitempty"`          // 服务端口
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_rpc_service_discovery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_discovery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_rpc_service_discovery_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceInfo) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

func (x *ServiceInfo) GetServicePort() string {
	if x != nil {
		return x.ServicePort
	}
	return ""
}

var File_rpc_service_discovery_proto protoreflect.FileDescriptor

const file_rpc_service_discovery_proto_rawDesc = "" +
	"\n" +
	"\x1brpc/service/discovery.proto\x12\tdiscovery\"\x80\x01\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_address\x18\x02 \x01(\tR\x0eserviceAddress\x12!\n" +
	"\fservice_port\x18\x03 \x01(\tR\vservicePort\"\x12\n" +
	"\x10RegisterResponse\"\x82\x01\n" +
	"\x11DeregisterRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_address\x18\x02 \x01(\tR\x0eserviceAddress\x12!\n" +
	"\fservice_port\x18\x03 \x01(\tR\vservicePort\"\x14\n" +
	"\x12DeregisterResponse\"6\n" +
	"\x11GetServiceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"O\n" +
	"\x12GetServiceResponse\x129\n" +
	"\fservice_info\x18\x01 \x03(\v2\x16.discovery.ServiceInfoR\vserviceInfo\"W\n" +
	"\x13GetServiceIPRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"client_key\x18\x02 \x01(\tR\tclientKey\"b\n" +
	"\x14GetServiceIPResponse\x12'\n" +
	"\x0fservice_address\x18\x01 \x01(\tR\x0eserviceAddress\x12!\n" +
	"\fservice_port\x18\x02 \x01(\tR\vservicePort\"\x0e\n" +
	"\fReadyRequest\"%\n" +
	"\rReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"Y\n" +
	"\vServiceInfo\x12'\n" +
	"\x0fservice_address\x18\x01 \x01(\tR\x0eserviceAddress\x12!\n" +
	"\fservice_port\x18\x02 \x01(\tR\vservicePort2\xf3\x02\n" +
	"\tDiscovery\x12C\n" +
	"\bRegister\x12\x1a.discovery.RegisterRequest\x1a\x1b.discovery.RegisterResponse\x12I\n" +
	"\n" +
	"Deregister\x12\x1c.discovery.DeregisterRequest\x1a\x1d.discovery.DeregisterResponse\x12I\n" +
	"\n" +
	"GetService\x12\x1c.discovery.GetServiceRequest\x1a\x1d.discovery.GetServiceResponse\x12O\n" +
	"\fGetServiceIP\x12\x1e.discovery.GetServiceIPRequest\x1a\x1f.discovery.GetServiceIPResponse\x12:\n" +
	"\x05Ready\x12\x17.discovery.ReadyRequest\x1a\x18.discovery.ReadyResponseB\fZ\n" +
	"./;serviceb\x06proto3"

var (
	file_rpc_service_discovery_proto_rawDescOnce sync.Once
	file_rpc_service_discovery_proto_rawDescData []byte
)

func file_rpc_service_discovery_proto_rawDescGZIP() []byte {
	file_rpc_service_discovery_proto_rawDescOnce.Do(func() {
		file_rpc_service_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_service_discovery_proto_rawDesc), len(file_rpc_service_discovery_proto_rawDesc)))
	})
	return file_rpc_service_discovery_proto_rawDescData
}

var file_rpc_service_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpc_service_discovery_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: discovery.RegisterRequest
	(*RegisterResponse)(nil),     // 1: discovery.RegisterResponse
	(*DeregisterRequest)(nil),    // 2: discovery.DeregisterRequest
	(*DeregisterResponse)(nil),   // 3: discovery.DeregisterResponse
	(*GetServiceRequest)(nil),    // 4: discovery.GetServiceRequest
	(*GetServiceResponse)(nil),   // 5: discovery.GetServiceResponse
	(*GetServiceIPRequest)(nil),  // 6: discovery.GetServiceIPRequest
	(*GetServiceIPResponse)(nil), // 7: discovery.GetServiceIPResponse
	(*ReadyRequest)(nil),         // 8: discovery.ReadyRequest
	(*ReadyResponse)(nil),        // 9: discovery.ReadyResponse
	(*ServiceInfo)(nil),          // 10: discovery.ServiceInfo
}
var file_rpc_service_discovery_proto_depIdxs = []int32{
	10, // 0: discovery.GetServiceResponse.service_info:type_name -> discovery.ServiceInfo
	0,  // 1: discovery.Discovery.Register:input_type -> discovery.RegisterRequest
	2,  // 2: discovery.Discovery.Deregister:input_type -> discovery.DeregisterRequest
	4,  // 3: discovery.Discovery.GetService:input_type -> discovery.GetServiceRequest
	6,  // 4: discovery.Discovery.GetServiceIP:input_type -> discovery.GetServiceIPRequest
	8,  // 5: discovery.Discovery.Ready:input_type -> discovery.ReadyRequest
	1,  // 6: discovery.Discovery.Register:output_type -> discovery.RegisterResponse
	3,  // 7: discovery.Discovery.Deregister:output_type -> discovery.DeregisterResponse
	5,  // 8: discovery.Discovery.GetService:output_type -> discovery.GetServiceResponse
	7,  // 9: discovery.Discovery.GetServiceIP:output_type -> discovery.GetServiceIPResponse
	9,  // 10: discovery.Discovery.Ready:output_type -> discovery.ReadyResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_service_discovery_proto_init() }
func file_rpc_service_discovery_proto_init() {
	if File_rpc_service_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_service_discovery_proto_rawDesc), len(file_rpc_service_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_service_discovery_proto_goTypes,
		DependencyIndexes: file_rpc_service_discovery_proto_depIdxs,
		MessageInfos:      file_rpc_service_discovery_proto_msgTypes,
	}.Build()
	File_rpc_service_discovery_proto = out.File
	file_rpc_service_discovery_proto_goTypes = nil
	file_rpc_service_discovery_proto_depIdxs = nil
}
