// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: rpc/service/apigateway.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoryMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionUuid   string                 `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"` // 会话UUID
	StartSeqid    int64                  `protobuf:"varint,2,opt,name=start_seqid,json=startSeqid,proto3" json:"start_seqid,omitempty"`   // 开始序列号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryMessageRequest) Reset() {
	*x = HistoryMessageRequest{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryMessageRequest) ProtoMessage() {}

func (x *HistoryMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryMessageRequest.ProtoReflect.Descriptor instead.
func (*HistoryMessageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryMessageRequest) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *HistoryMessageRequest) GetStartSeqid() int64 {
	if x != nil {
		return x.StartSeqid
	}
	return 0
}

type HistoryMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"` // 消息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryMessageResponse) Reset() {
	*x = HistoryMessageResponse{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryMessageResponse) ProtoMessage() {}

func (x *HistoryMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryMessageResponse.ProtoReflect.Descriptor instead.
func (*HistoryMessageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryMessageResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetSessionUserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionUuid   string                 `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"` // 会话UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionUserListRequest) Reset() {
	*x = GetSessionUserListRequest{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionUserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionUserListRequest) ProtoMessage() {}

func (x *GetSessionUserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionUserListRequest.ProtoReflect.Descriptor instead.
func (*GetSessionUserListRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionUserListRequest) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

type GetSessionUserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*SessionUserListItem `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` // 会话用户UUID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionUserListResponse) Reset() {
	*x = GetSessionUserListResponse{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionUserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionUserListResponse) ProtoMessage() {}

func (x *GetSessionUserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionUserListResponse.ProtoReflect.Descriptor instead.
func (*GetSessionUserListResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionUserListResponse) GetUsers() []*SessionUserListItem {
	if x != nil {
		return x.Users
	}
	return nil
}

type SessionUserListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`       // 用户UUID
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`       // 用户名称
	UserAvatar    string                 `protobuf:"bytes,3,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"` // 用户头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionUserListItem) Reset() {
	*x = SessionUserListItem{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionUserListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUserListItem) ProtoMessage() {}

func (x *SessionUserListItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionUserListItem.ProtoReflect.Descriptor instead.
func (*SessionUserListItem) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{4}
}

func (x *SessionUserListItem) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *SessionUserListItem) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SessionUserListItem) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageUuid   string                 `protobuf:"bytes,1,opt,name=message_uuid,json=messageUuid,proto3" json:"message_uuid,omitempty"`    // 消息UUID
	SessionUuid   string                 `protobuf:"bytes,2,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`    // 会话UUID
	SeqId         int64                  `protobuf:"varint,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`                     // 消息序列号ID
	MessageType   int64                  `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`   // 消息类型
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                               // 消息内容
	SenderUuid    string                 `protobuf:"bytes,6,opt,name=sender_uuid,json=senderUuid,proto3" json:"sender_uuid,omitempty"`       // 消息发送者UUID
	SenderName    string                 `protobuf:"bytes,7,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`       // 消息发送者名称
	SenderAvatar  string                 `protobuf:"bytes,8,opt,name=sender_avatar,json=senderAvatar,proto3" json:"sender_avatar,omitempty"` // 消息发送者头像
	SendTime      string                 `protobuf:"bytes,9,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`             // 消息时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetMessageUuid() string {
	if x != nil {
		return x.MessageUuid
	}
	return ""
}

func (x *Message) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *Message) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *Message) GetMessageType() int64 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetSenderUuid() string {
	if x != nil {
		return x.SenderUuid
	}
	return ""
}

func (x *Message) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Message) GetSenderAvatar() string {
	if x != nil {
		return x.SenderAvatar
	}
	return ""
}

func (x *Message) GetSendTime() string {
	if x != nil {
		return x.SendTime
	}
	return ""
}

type SessionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionListRequest) Reset() {
	*x = SessionListRequest{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionListRequest) ProtoMessage() {}

func (x *SessionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionListRequest.ProtoReflect.Descriptor instead.
func (*SessionListRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{6}
}

type SessionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"` // 会话列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionListResponse) Reset() {
	*x = SessionListResponse{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionListResponse) ProtoMessage() {}

func (x *SessionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionListResponse.ProtoReflect.Descriptor instead.
func (*SessionListResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{7}
}

func (x *SessionListResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                   // 会话UUID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                   // 会话名称
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                               // 会话头像
	LastMessage   string                 `protobuf:"bytes,4,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`  // 最后一条消息
	LastTime      string                 `protobuf:"bytes,5,opt,name=last_time,json=lastTime,proto3" json:"last_time,omitempty"`           // 最后一条消息时间
	UnreadCount   int64                  `protobuf:"varint,6,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"` // 未读消息数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{8}
}

func (x *Session) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Session) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

func (x *Session) GetLastTime() string {
	if x != nil {
		return x.LastTime
	}
	return ""
}

func (x *Session) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                          // 标识符 账号/手机号/邮箱
	Credential    string                 `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`                          // 凭证 密码/验证码/access_token
	IdentityType  int64                  `protobuf:"varint,3,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"` // 身份类型 1: 手机号 2: 邮箱 3: 用户名 4: wechat 5: google 6: facebook 7: github
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{9}
}

func (x *LoginRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *LoginRequest) GetIdentityType() int64 {
	if x != nil {
		return x.IdentityType
	}
	return 0
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                   // 令牌
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // 刷新令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{10}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`                          // 标识符 账号/手机号/邮箱
	Credential    string                 `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`                          // 凭证 密码/验证码/access_token
	IdentityType  int64                  `protobuf:"varint,3,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"` // 身份类型 1: 手机号 2: 邮箱 3: 用户名 4: wechat 5: google 6: facebook 7: github
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *RegisterRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *RegisterRequest) GetIdentityType() int64 {
	if x != nil {
		return x.IdentityType
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                   // 令牌
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // 刷新令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionUuid   string                 `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`  // 会话UUID
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                             // 消息
	SenderUuid    string                 `protobuf:"bytes,3,opt,name=sender_uuid,json=senderUuid,proto3" json:"sender_uuid,omitempty"`     // 消息发送者UUID
	MessageType   int64                  `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // 消息类型
	SeqId         int64                  `protobuf:"varint,5,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`                   // 消息序列号ID
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                        // 消息时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{13}
}

func (x *SendMessageRequest) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *SendMessageRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SendMessageRequest) GetSenderUuid() string {
	if x != nil {
		return x.SenderUuid
	}
	return ""
}

func (x *SendMessageRequest) GetMessageType() int64 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *SendMessageRequest) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *SendMessageRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageUuid   string                 `protobuf:"bytes,1,opt,name=message_uuid,json=messageUuid,proto3" json:"message_uuid,omitempty"` // 消息UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{14}
}

func (x *SendMessageResponse) GetMessageUuid() string {
	if x != nil {
		return x.MessageUuid
	}
	return ""
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{15}
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`     // 用户UUID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`     // 用户名称
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"` // 用户头像
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`   // 用户邮箱
	Mobile        string                 `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"` // 用户手机号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_rpc_service_apigateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_apigateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_apigateway_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserInfoResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetUserInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserInfoResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

var File_rpc_service_apigateway_proto protoreflect.FileDescriptor

const file_rpc_service_apigateway_proto_rawDesc = "" +
	"\n" +
	"\x1crpc/service/apigateway.proto\x12\n" +
	"apigateway\"[\n" +
	"\x15HistoryMessageRequest\x12!\n" +
	"\fsession_uuid\x18\x01 \x01(\tR\vsessionUuid\x12\x1f\n" +
	"\vstart_seqid\x18\x02 \x01(\x03R\n" +
	"startSeqid\"I\n" +
	"\x16HistoryMessageResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.apigateway.MessageR\bmessages\">\n" +
	"\x19GetSessionUserListRequest\x12!\n" +
	"\fsession_uuid\x18\x01 \x01(\tR\vsessionUuid\"S\n" +
	"\x1aGetSessionUserListResponse\x125\n" +
	"\x05users\x18\x01 \x03(\v2\x1f.apigateway.SessionUserListItemR\x05users\"p\n" +
	"\x13SessionUserListItem\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1f\n" +
	"\vuser_avatar\x18\x03 \x01(\tR\n" +
	"userAvatar\"\xa7\x02\n" +
	"\aMessage\x12!\n" +
	"\fmessage_uuid\x18\x01 \x01(\tR\vmessageUuid\x12!\n" +
	"\fsession_uuid\x18\x02 \x01(\tR\vsessionUuid\x12\x15\n" +
	"\x06seq_id\x18\x03 \x01(\x03R\x05seqId\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\x03R\vmessageType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1f\n" +
	"\vsender_uuid\x18\x06 \x01(\tR\n" +
	"senderUuid\x12\x1f\n" +
	"\vsender_name\x18\a \x01(\tR\n" +
	"senderName\x12#\n" +
	"\rsender_avatar\x18\b \x01(\tR\fsenderAvatar\x12\x1b\n" +
	"\tsend_time\x18\t \x01(\tR\bsendTime\"\x14\n" +
	"\x12SessionListRequest\"F\n" +
	"\x13SessionListResponse\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.apigateway.SessionR\bsessions\"\xac\x01\n" +
	"\aSession\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12!\n" +
	"\flast_message\x18\x04 \x01(\tR\vlastMessage\x12\x1b\n" +
	"\tlast_time\x18\x05 \x01(\tR\blastTime\x12!\n" +
	"\funread_count\x18\x06 \x01(\x03R\vunreadCount\"s\n" +
	"\fLoginRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\tR\n" +
	"credential\x12#\n" +
	"\ridentity_type\x18\x03 \x01(\x03R\fidentityType\"J\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"v\n" +
	"\x0fRegisterRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\tR\n" +
	"credential\x12#\n" +
	"\ridentity_type\x18\x03 \x01(\x03R\fidentityType\"M\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\xca\x01\n" +
	"\x12SendMessageRequest\x12!\n" +
	"\fsession_uuid\x18\x01 \x01(\tR\vsessionUuid\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1f\n" +
	"\vsender_uuid\x18\x03 \x01(\tR\n" +
	"senderUuid\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\x03R\vmessageType\x12\x15\n" +
	"\x06seq_id\x18\x05 \x01(\x03R\x05seqId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"8\n" +
	"\x13SendMessageResponse\x12!\n" +
	"\fmessage_uuid\x18\x01 \x01(\tR\vmessageUuid\"\x14\n" +
	"\x12GetUserInfoRequest\"\x83\x01\n" +
	"\x13GetUserInfoResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x05 \x01(\tR\x06mobile2\xbf\x04\n" +
	"\n" +
	"APIGateway\x12N\n" +
	"\vSessionList\x12\x1e.apigateway.SessionListRequest\x1a\x1f.apigateway.SessionListResponse\x12c\n" +
	"\x12GetSessionUserList\x12%.apigateway.GetSessionUserListRequest\x1a&.apigateway.GetSessionUserListResponse\x12W\n" +
	"\x0eHistoryMessage\x12!.apigateway.HistoryMessageRequest\x1a\".apigateway.HistoryMessageResponse\x12<\n" +
	"\x05Login\x12\x18.apigateway.LoginRequest\x1a\x19.apigateway.LoginResponse\x12E\n" +
	"\bRegister\x12\x1b.apigateway.RegisterRequest\x1a\x1c.apigateway.RegisterResponse\x12N\n" +
	"\vSendMessage\x12\x1e.apigateway.SendMessageRequest\x1a\x1f.apigateway.SendMessageResponse\x12N\n" +
	"\vGetUserInfo\x12\x1e.apigateway.GetUserInfoRequest\x1a\x1f.apigateway.GetUserInfoResponseB\fZ\n" +
	"./;serviceb\x06proto3"

var (
	file_rpc_service_apigateway_proto_rawDescOnce sync.Once
	file_rpc_service_apigateway_proto_rawDescData []byte
)

func file_rpc_service_apigateway_proto_rawDescGZIP() []byte {
	file_rpc_service_apigateway_proto_rawDescOnce.Do(func() {
		file_rpc_service_apigateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_service_apigateway_proto_rawDesc), len(file_rpc_service_apigateway_proto_rawDesc)))
	})
	return file_rpc_service_apigateway_proto_rawDescData
}

var file_rpc_service_apigateway_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_rpc_service_apigateway_proto_goTypes = []any{
	(*HistoryMessageRequest)(nil),      // 0: apigateway.HistoryMessageRequest
	(*HistoryMessageResponse)(nil),     // 1: apigateway.HistoryMessageResponse
	(*GetSessionUserListRequest)(nil),  // 2: apigateway.GetSessionUserListRequest
	(*GetSessionUserListResponse)(nil), // 3: apigateway.GetSessionUserListResponse
	(*SessionUserListItem)(nil),        // 4: apigateway.SessionUserListItem
	(*Message)(nil),                    // 5: apigateway.Message
	(*SessionListRequest)(nil),         // 6: apigateway.SessionListRequest
	(*SessionListResponse)(nil),        // 7: apigateway.SessionListResponse
	(*Session)(nil),                    // 8: apigateway.Session
	(*LoginRequest)(nil),               // 9: apigateway.LoginRequest
	(*LoginResponse)(nil),              // 10: apigateway.LoginResponse
	(*RegisterRequest)(nil),            // 11: apigateway.RegisterRequest
	(*RegisterResponse)(nil),           // 12: apigateway.RegisterResponse
	(*SendMessageRequest)(nil),         // 13: apigateway.SendMessageRequest
	(*SendMessageResponse)(nil),        // 14: apigateway.SendMessageResponse
	(*GetUserInfoRequest)(nil),         // 15: apigateway.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),        // 16: apigateway.GetUserInfoResponse
}
var file_rpc_service_apigateway_proto_depIdxs = []int32{
	5,  // 0: apigateway.HistoryMessageResponse.messages:type_name -> apigateway.Message
	4,  // 1: apigateway.GetSessionUserListResponse.users:type_name -> apigateway.SessionUserListItem
	8,  // 2: apigateway.SessionListResponse.sessions:type_name -> apigateway.Session
	6,  // 3: apigateway.APIGateway.SessionList:input_type -> apigateway.SessionListRequest
	2,  // 4: apigateway.APIGateway.GetSessionUserList:input_type -> apigateway.GetSessionUserListRequest
	0,  // 5: apigateway.APIGateway.HistoryMessage:input_type -> apigateway.HistoryMessageRequest
	9,  // 6: apigateway.APIGateway.Login:input_type -> apigateway.LoginRequest
	11, // 7: apigateway.APIGateway.Register:input_type -> apigateway.RegisterRequest
	13, // 8: apigateway.APIGateway.SendMessage:input_type -> apigateway.SendMessageRequest
	15, // 9: apigateway.APIGateway.GetUserInfo:input_type -> apigateway.GetUserInfoRequest
	7,  // 10: apigateway.APIGateway.SessionList:output_type -> apigateway.SessionListResponse
	3,  // 11: apigateway.APIGateway.GetSessionUserList:output_type -> apigateway.GetSessionUserListResponse
	1,  // 12: apigateway.APIGateway.HistoryMessage:output_type -> apigateway.HistoryMessageResponse
	10, // 13: apigateway.APIGateway.Login:output_type -> apigateway.LoginResponse
	12, // 14: apigateway.APIGateway.Register:output_type -> apigateway.RegisterResponse
	14, // 15: apigateway.APIGateway.SendMessage:output_type -> apigateway.SendMessageResponse
	16, // 16: apigateway.APIGateway.GetUserInfo:output_type -> apigateway.GetUserInfoResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_service_apigateway_proto_init() }
func file_rpc_service_apigateway_proto_init() {
	if File_rpc_service_apigateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_service_apigateway_proto_rawDesc), len(file_rpc_service_apigateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_service_apigateway_proto_goTypes,
		DependencyIndexes: file_rpc_service_apigateway_proto_depIdxs,
		MessageInfos:      file_rpc_service_apigateway_proto_msgTypes,
	}.Build()
	File_rpc_service_apigateway_proto = out.File
	file_rpc_service_apigateway_proto_goTypes = nil
	file_rpc_service_apigateway_proto_depIdxs = nil
}
